// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 14:40:27 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteam_wsd;

public interface IgetTeam_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteam_wsd.getTeamResponse getTeam( com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteam_wsd.getTeam getTeam );
  }
