// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Dec 20 17:18:59 GMT 2010

package com.webmethods.caf.is.wsclient.steps_ui_core.previouscases.wsd.getpreviouscases_wsd;

public class getPreviousCasesResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.steps_ui_core.previouscases.wsd.getpreviouscases_wsd.Case[] PreviousCases;
  private java.lang.String error_boolean;
  private java.lang.String error_text;

  public com.webmethods.caf.is.wsclient.steps_ui_core.previouscases.wsd.getpreviouscases_wsd.Case[] getPreviousCases()
    {
    return PreviousCases;
    }

  public void setPreviousCases( com.webmethods.caf.is.wsclient.steps_ui_core.previouscases.wsd.getpreviouscases_wsd.Case[] value )
    {
    this.PreviousCases = value;
    }

  public java.lang.String getError_boolean()
    {
    return error_boolean;
    }

  public void setError_boolean( java.lang.String value )
    {
    this.error_boolean = value;
    }

  public java.lang.String getError_text()
    {
    return error_text;
    }

  public void setError_text( java.lang.String value )
    {
    this.error_text = value;
    }
  }
