// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Feb 21 10:39:50 GMT 2011

package com.webmethods.caf.is.wsclient.steps_ui_common.wsd.sharedmessaging.createerrortag_wsd;

public class createErrorTag implements java.io.Serializable
  {
  private java.lang.String title;
  private java.lang.String style;
  private java.lang.String message;

  public java.lang.String getTitle()
    {
    return title;
    }

  public void setTitle( java.lang.String value )
    {
    this.title = value;
    }

  public java.lang.String getStyle()
    {
    return style;
    }

  public void setStyle( java.lang.String value )
    {
    this.style = value;
    }

  public java.lang.String getMessage()
    {
    return message;
    }

  public void setMessage( java.lang.String value )
    {
    this.message = value;
    }
  }
