// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Feb 21 10:39:50 GMT 2011

package com.webmethods.caf.is.wsclient.steps_ui_common.wsd.sharedmessaging.createerrortag_wsd;

public interface IcreateErrorTag_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.steps_ui_common.wsd.sharedmessaging.createerrortag_wsd.createErrorTagResponse createErrorTag( com.webmethods.caf.is.wsclient.steps_ui_common.wsd.sharedmessaging.createerrortag_wsd.createErrorTag createErrorTag );
  }
