// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 14:40:27 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteam_wsd;

public class getTeam implements java.io.Serializable
  {
  private java.lang.String employee_in;

  public java.lang.String getEmployee_in()
    {
    return employee_in;
    }

  public void setEmployee_in( java.lang.String value )
    {
    this.employee_in = value;
    }
  }
