// generated by Glue 8.0 Fix 7 build 2 (wsdl2java) on Wed Sep 02 10:57:07 BST 2015

package com.webmethods.caf.wsclient.steps_ui_utilities.wsd.runutilityfeestatusreport2012institution_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class runUtilityFeeStatusReport2012Institution_WSDHelper
  {
  public static IrunUtilityFeeStatusReport2012Institution_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/workspaces95/workspace95_DEFAULT/STEPS_UI_Utilities/src/com/webmethods/caf/wsclient/steps_ui_utilities/wsd/runutilityfeestatusreport2012institution_wsd/runUtilityFeeStatusReport2012Institution_WSD.wsdl" );
    }

  public static IrunUtilityFeeStatusReport2012Institution_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IrunUtilityFeeStatusReport2012Institution_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IrunUtilityFeeStatusReport2012Institution_WSD_PortType) Registry.bind( url, IrunUtilityFeeStatusReport2012Institution_WSD_PortType.class, context );
    }
  }
