// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 15:45:24 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteams_wsd;

public class getTeamsResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteams_wsd.GenericDD[] Teams;
  private java.lang.String error_boolean;
  private java.lang.String error_text;

  public com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteams_wsd.GenericDD[] getTeams()
    {
    return Teams;
    }

  public void setTeams( com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteams_wsd.GenericDD[] value )
    {
    this.Teams = value;
    }

  public java.lang.String getError_boolean()
    {
    return error_boolean;
    }

  public void setError_boolean( java.lang.String value )
    {
    this.error_boolean = value;
    }

  public java.lang.String getError_text()
    {
    return error_text;
    }

  public void setError_text( java.lang.String value )
    {
    this.error_text = value;
    }
  }
