// generated by Glue 8.0 Fix 7 build 2 (wsdl2java) on Wed Sep 02 10:42:53 BST 2015

package com.webmethods.caf.wsclient.steps_ui_utilities.wsd.runutilityfeestatusreport2012all_wsd;

import electric.util.async.Async;

public interface IrunUtilityFeeStatusReport2012All_WSD_PortType
  {
  public void runUtilityFeeStatusReport2012All( com.webmethods.caf.wsclient.steps_ui_utilities.wsd.runutilityfeestatusreport2012all_wsd.runUtilityFeeStatusReport2012All runUtilityFeeStatusReport2012All , Async result );
  }
