// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Feb 21 10:39:50 GMT 2011

package com.webmethods.caf.is.wsclient.steps_ui_common.wsd.sharedmessaging.createerrortag_wsd;

public class createErrorTagResponse implements java.io.Serializable
  {
  private java.lang.String sharedMessage;

  public java.lang.String getSharedMessage()
    {
    return sharedMessage;
    }

  public void setSharedMessage( java.lang.String value )
    {
    this.sharedMessage = value;
    }
  }
