// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 16:46:49 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getalluserdetails_wsd;

public class UserDetail implements java.io.Serializable
  {
  private java.lang.String USERNAME;
  private java.lang.String FORENAME;
  private java.lang.String SURNAME;
  private java.lang.String TEAM;
  private java.lang.String LAST_UPDATED_BY;
  private java.util.Date LAST_UPDATED_ON;

  public java.lang.String getUSERNAME()
    {
    return USERNAME;
    }

  public void setUSERNAME( java.lang.String value )
    {
    this.USERNAME = value;
    }

  public java.lang.String getFORENAME()
    {
    return FORENAME;
    }

  public void setFORENAME( java.lang.String value )
    {
    this.FORENAME = value;
    }

  public java.lang.String getSURNAME()
    {
    return SURNAME;
    }

  public void setSURNAME( java.lang.String value )
    {
    this.SURNAME = value;
    }

  public java.lang.String getTEAM()
    {
    return TEAM;
    }

  public void setTEAM( java.lang.String value )
    {
    this.TEAM = value;
    }

  public java.lang.String getLAST_UPDATED_BY()
    {
    return LAST_UPDATED_BY;
    }

  public void setLAST_UPDATED_BY( java.lang.String value )
    {
    this.LAST_UPDATED_BY = value;
    }

  public java.util.Date getLAST_UPDATED_ON()
    {
    return LAST_UPDATED_ON;
    }

  public void setLAST_UPDATED_ON( java.util.Date value )
    {
    this.LAST_UPDATED_ON = value;
    }
  }
