// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Dec 20 17:18:59 GMT 2010

package com.webmethods.caf.is.wsclient.steps_ui_core.previouscases.wsd.getpreviouscases_wsd;

public class Case implements java.io.Serializable
  {
  private java.lang.String stud_ref_no;
  private java.util.Date date_entered;

  public java.lang.String getStud_ref_no()
    {
    return stud_ref_no;
    }

  public void setStud_ref_no( java.lang.String value )
    {
    this.stud_ref_no = value;
    }

  public java.util.Date getDate_entered()
    {
    return date_entered;
    }

  public void setDate_entered( java.util.Date value )
    {
    this.date_entered = value;
    }
  }
