// generated by Glue 8.0 Fix 7 build 2 (wsdl2java) on Wed Sep 02 10:57:07 BST 2015

package com.webmethods.caf.wsclient.steps_ui_utilities.wsd.runutilityfeestatusreport2012institution_wsd;

import electric.util.async.Async;

public interface IrunUtilityFeeStatusReport2012Institution_WSD_PortType
  {
  public void runUtilityFeeStatusReport2012Institution( com.webmethods.caf.wsclient.steps_ui_utilities.wsd.runutilityfeestatusreport2012institution_wsd.runUtilityFeeStatusReport2012Institution runUtilityFeeStatusReport2012Institution , Async result );
  }
