// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Dec 20 17:18:59 GMT 2010

package com.webmethods.caf.is.wsclient.steps_ui_core.previouscases.wsd.getpreviouscases_wsd;

public interface IgetPreviousCases_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.steps_ui_core.previouscases.wsd.getpreviouscases_wsd.getPreviousCasesResponse getPreviousCases( com.webmethods.caf.is.wsclient.steps_ui_core.previouscases.wsd.getpreviouscases_wsd.getPreviousCases getPreviousCases );
  }
