// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 14:40:27 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteam_wsd;

public class getTeamResponse implements java.io.Serializable
  {
  private java.lang.String team_out;
  private java.lang.String error_boolean;
  private java.lang.String error_text;

  public java.lang.String getTeam_out()
    {
    return team_out;
    }

  public void setTeam_out( java.lang.String value )
    {
    this.team_out = value;
    }

  public java.lang.String getError_boolean()
    {
    return error_boolean;
    }

  public void setError_boolean( java.lang.String value )
    {
    this.error_boolean = value;
    }

  public java.lang.String getError_text()
    {
    return error_text;
    }

  public void setError_text( java.lang.String value )
    {
    this.error_text = value;
    }
  }
