// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 14:40:02 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.setteam_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class setTeam_WSDHelper
  {
  public static IsetTeam_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/DesignerWorkspace/STEPS_UI_User/src/com/webmethods/caf/is/wsclient/steps_ui_core/team/wsd/setteam_wsd/setTeam_WSD.wsdl" );
    }

  public static IsetTeam_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IsetTeam_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IsetTeam_WSD_PortType) Registry.bind( url, IsetTeam_WSD_PortType.class, context );
    }
  }
