// generated by Glue 8.0 Fix 7 build 2 (wsdl2java) on Tue Sep 01 17:35:06 BST 2015

package com.webmethods.caf.wsclient.steps_ui_utilities.wsd.runutilitybatchrecalc_wsd;

public class runUtilityBatchRecalc implements java.io.Serializable
  {
  }
