// generated by Glue 8.0 Fix 7 build 2 (wsdl2java) on Tue Sep 01 17:35:06 BST 2015

package com.webmethods.caf.wsclient.steps_ui_utilities.wsd.runutilitybatchrecalc_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class runUtilityBatchRecalc_WSDHelper
  {
  public static IrunUtilityBatchRecalc_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/workspaces95/workspace95_DEFAULT/STEPS_UI_Utilities/src/com/webmethods/caf/wsclient/steps_ui_utilities/wsd/runutilitybatchrecalc_wsd/runUtilityBatchRecalc_WSD.wsdl" );
    }

  public static IrunUtilityBatchRecalc_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IrunUtilityBatchRecalc_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IrunUtilityBatchRecalc_WSD_PortType) Registry.bind( url, IrunUtilityBatchRecalc_WSD_PortType.class, context );
    }
  }
