// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 16:46:49 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getalluserdetails_wsd;

public interface IgetAllUserDetails_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getalluserdetails_wsd.getAllUserDetailsResponse getAllUserDetails( com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getalluserdetails_wsd.getAllUserDetails getAllUserDetails );
  }
