// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 16:25:07 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_common.wsd.sharedmessaging.createerrortag_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class createErrorTag_WSDHelper
  {
  public static IcreateErrorTag_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/DesignerWorkspace/STEPS_UI_User/src/com/webmethods/caf/is/wsclient/steps_ui_common/wsd/sharedmessaging/createerrortag_wsd/createErrorTag_WSD.wsdl" );
    }

  public static IcreateErrorTag_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IcreateErrorTag_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IcreateErrorTag_WSD_PortType) Registry.bind( url, IcreateErrorTag_WSD_PortType.class, context );
    }
  }
