// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 14:40:02 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.setteam_wsd;

public class setTeam implements java.io.Serializable
  {
  private java.lang.String team_in;
  private java.lang.String username_in;
  private java.lang.String employee_in;

  public java.lang.String getTeam_in()
    {
    return team_in;
    }

  public void setTeam_in( java.lang.String value )
    {
    this.team_in = value;
    }

  public java.lang.String getUsername_in()
    {
    return username_in;
    }

  public void setUsername_in( java.lang.String value )
    {
    this.username_in = value;
    }

  public java.lang.String getEmployee_in()
    {
    return employee_in;
    }

  public void setEmployee_in( java.lang.String value )
    {
    this.employee_in = value;
    }
  }
