// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 15:45:24 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteams_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class getTeams_WSDHelper
  {
  public static IgetTeams_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/DesignerWorkspace/STEPS_UI_User/src/com/webmethods/caf/is/wsclient/steps_ui_core/team/wsd/getteams_wsd/getTeams_WSD.wsdl" );
    }

  public static IgetTeams_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IgetTeams_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IgetTeams_WSD_PortType) Registry.bind( url, IgetTeams_WSD_PortType.class, context );
    }
  }
