// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 15:45:24 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteams_wsd;

public interface IgetTeams_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteams_wsd.getTeamsResponse getTeams( com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteams_wsd.getTeams getTeams );
  }
