// generated by Glue 8.0 Fix 7 build 2 (wsdl2java) on Wed Sep 02 10:42:53 BST 2015

package com.webmethods.caf.wsclient.steps_ui_utilities.wsd.runutilityfeestatusreport2012all_wsd;

public class runUtilityFeeStatusReport2012All implements java.io.Serializable
  {
  }
