// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Wed Jan 04 13:20:56 GMT 2012

package com.webmethods.caf.is.wsclient.steps_ui_student.navigation.wsd.getstudentsessions_wsd;

public class getStudentSessions implements java.io.Serializable
  {
  private java.lang.String stud_ref_no_in;

  public java.lang.String getStud_ref_no_in()
    {
    return stud_ref_no_in;
    }

  public void setStud_ref_no_in( java.lang.String value )
    {
    this.stud_ref_no_in = value;
    }
  }
