// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Wed Jan 04 13:20:56 GMT 2012

package com.webmethods.caf.is.wsclient.steps_ui_student.navigation.wsd.getstudentsessions_wsd;

public class getStudentSessionsResponse implements java.io.Serializable
  {
  private com.webmethods.caf.is.wsclient.steps_ui_student.navigation.wsd.getstudentsessions_wsd.StudSessions[] studsessions;
  private java.lang.String error_boolean;
  private java.lang.String error_text;

  public com.webmethods.caf.is.wsclient.steps_ui_student.navigation.wsd.getstudentsessions_wsd.StudSessions[] getStudsessions()
    {
    return studsessions;
    }

  public void setStudsessions( com.webmethods.caf.is.wsclient.steps_ui_student.navigation.wsd.getstudentsessions_wsd.StudSessions[] value )
    {
    this.studsessions = value;
    }

  public java.lang.String getError_boolean()
    {
    return error_boolean;
    }

  public void setError_boolean( java.lang.String value )
    {
    this.error_boolean = value;
    }

  public java.lang.String getError_text()
    {
    return error_text;
    }

  public void setError_text( java.lang.String value )
    {
    this.error_text = value;
    }
  }
