// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Wed Jan 04 13:20:56 GMT 2012

package com.webmethods.caf.is.wsclient.steps_ui_student.navigation.wsd.getstudentsessions_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class getStudentSessions_WSDHelper
  {
  public static IgetStudentSessions_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/DesignerWorkspace/STEPS_UI_CaseworkerTools/src/com/webmethods/caf/is/wsclient/steps_ui_student/navigation/wsd/getstudentsessions_wsd/getStudentSessions_WSD.wsdl" );
    }

  public static IgetStudentSessions_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IgetStudentSessions_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IgetStudentSessions_WSD_PortType) Registry.bind( url, IgetStudentSessions_WSD_PortType.class, context );
    }
  }
