// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Wed Jan 04 13:20:56 GMT 2012

package com.webmethods.caf.is.wsclient.steps_ui_student.navigation.wsd.getstudentsessions_wsd;

public interface IgetStudentSessions_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.steps_ui_student.navigation.wsd.getstudentsessions_wsd.getStudentSessionsResponse getStudentSessions( com.webmethods.caf.is.wsclient.steps_ui_student.navigation.wsd.getstudentsessions_wsd.getStudentSessions getStudentSessions );
  }
