// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Wed Jan 04 13:20:56 GMT 2012

package com.webmethods.caf.is.wsclient.steps_ui_student.navigation.wsd.getstudentsessions_wsd;

public class StudSessions implements java.io.Serializable
  {
  private java.lang.String stud_session_id;
  private java.lang.String db;
  private java.lang.String session_code;

  public java.lang.String getStud_session_id()
    {
    return stud_session_id;
    }

  public void setStud_session_id( java.lang.String value )
    {
    this.stud_session_id = value;
    }

  public java.lang.String getDb()
    {
    return db;
    }

  public void setDb( java.lang.String value )
    {
    this.db = value;
    }

  public java.lang.String getSession_code()
    {
    return session_code;
    }

  public void setSession_code( java.lang.String value )
    {
    this.session_code = value;
    }
  }
