// generated by Glue 8.0 Fix 7 build 2 (wsdl2java) on Tue Apr 12 11:16:37 BST 2016

package com.webmethods.caf.wsclient.steps_ui_utilities.wsd.rundsareminderletters_wsd;

public class runDSAReminderLetters implements java.io.Serializable
  {
  }
