// generated by Glue 8.0 Fix 7 build 2 (wsdl2java) on Tue Apr 12 11:16:37 BST 2016

package com.webmethods.caf.wsclient.steps_ui_utilities.wsd.rundsareminderletters_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class runDSAReminderLetters_WSDHelper
  {
  public static IrunDSAReminderLetters_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Users/BSU_User/workspace95/STEPS_UI_Utilities/src/com/webmethods/caf/wsclient/steps_ui_utilities/wsd/rundsareminderletters_wsd/runDSAReminderLetters_WSD.wsdl" );
    }

  public static IrunDSAReminderLetters_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IrunDSAReminderLetters_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IrunDSAReminderLetters_WSD_PortType) Registry.bind( url, IrunDSAReminderLetters_WSD_PortType.class, context );
    }
  }
