// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 15:45:24 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.getteams_wsd;

public class GenericDD implements java.io.Serializable
  {
  private java.lang.String value;
  private java.lang.String label;

  public java.lang.String getValue()
    {
    return value;
    }

  public void setValue( java.lang.String value )
    {
    this.value = value;
    }

  public java.lang.String getLabel()
    {
    return label;
    }

  public void setLabel( java.lang.String value )
    {
    this.label = value;
    }
  }
