// generated by Glue 8.0 Fix 7 build 2 (wsdl2java) on Wed Sep 02 10:57:07 BST 2015

package com.webmethods.caf.wsclient.steps_ui_utilities.wsd.runutilityfeestatusreport2012institution_wsd;

public class runUtilityFeeStatusReport2012Institution implements java.io.Serializable
  {
  private java.lang.String Inst_code;

  public java.lang.String getInst_code()
    {
    return Inst_code;
    }

  public void setInst_code( java.lang.String value )
    {
    this.Inst_code = value;
    }
  }
