// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Dec 20 17:18:59 GMT 2010

package com.webmethods.caf.is.wsclient.steps_ui_core.previouscases.wsd.getpreviouscases_wsd;

public class getPreviousCases implements java.io.Serializable
  {
  private java.lang.String employee_in;

  public java.lang.String getEmployee_in()
    {
    return employee_in;
    }

  public void setEmployee_in( java.lang.String value )
    {
    this.employee_in = value;
    }
  }
