// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Dec 20 17:18:59 GMT 2010

package com.webmethods.caf.is.wsclient.steps_ui_core.previouscases.wsd.getpreviouscases_wsd;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class getPreviousCases_WSDHelper
  {
  public static IgetPreviousCases_WSD_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/DesignerWorkspace/STEPS_UI_User/src/com/webmethods/caf/is/wsclient/steps_ui_core/previouscases/wsd/getpreviouscases_wsd/getPreviousCases_WSD.wsdl" );
    }

  public static IgetPreviousCases_WSD_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IgetPreviousCases_WSD_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IgetPreviousCases_WSD_PortType) Registry.bind( url, IgetPreviousCases_WSD_PortType.class, context );
    }
  }
