// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 14:40:02 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.setteam_wsd;

public interface IsetTeam_WSD_PortType
  {
  public com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.setteam_wsd.setTeamResponse setTeam( com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.setteam_wsd.setTeam setTeam );
  }
