// generated by Glue 6.5.1 Fix 4 build 5540 (wsdl2java) on Mon Apr 04 14:40:02 BST 2011

package com.webmethods.caf.is.wsclient.steps_ui_core.team.wsd.setteam_wsd;

public class setTeamResponse implements java.io.Serializable
  {
  private java.lang.String error_boolean;
  private java.lang.String error_text;

  public java.lang.String getError_boolean()
    {
    return error_boolean;
    }

  public void setError_boolean( java.lang.String value )
    {
    this.error_boolean = value;
    }

  public java.lang.String getError_text()
    {
    return error_text;
    }

  public void setError_text( java.lang.String value )
    {
    this.error_text = value;
    }
  }
